name = "sargraph-worker"
compatibility_date = "2025-05-28"
assets = { directory = "./build"}
routes = [ {pattern = "sargraph.xyz", custom_domain = true}]

[observability.logs]
enabled = true
invocation_logs = false