import readDataParallel from "./readDataParallel";
import pparseAllParallel from "./parseAllParallel";

function validateSarContent(fileContent) {
  // Reject binary files (null bytes)
  if (fileContent.includes("\0")) {
    throw new Error(
      "This appears to be a binary sa file.\nPlease provide a text-based sar file instead.\nYou can convert it with: sar -A -f <sa_file> > output.txt"
    );
  }

  const lines = fileContent.split("\n");
  const firstLine = lines.find((l) => l.trim().length > 0) || "";

  // SAR header always starts with "Linux"
  if (!firstLine.startsWith("Linux")) {
    throw new Error(
      "Invalid file format: the file does not start with a valid SAR header.\nPlease select a sar text file generated by sysstat."
    );
  }

  // Must contain at least a CPU section header
  const hasCpuSection = lines.some(
    (l) => l.includes("%usr") || l.includes("%user")
  );
  if (!hasCpuSection) {
    throw new Error(
      "The file appears to have a SAR header but is missing expected data sections (e.g. CPU).\nEnsure you are providing a complete sar output file."
    );
  }
}

function validateParsedResults(results) {
  const { cpuObject, fileDetails } = results;

  if (
    !fileDetails ||
    !fileDetails.hostname ||
    fileDetails.hostname === "N/A"
  ) {
    throw new Error(
      "Could not parse file metadata.\nThe file may be corrupted or in an unsupported format."
    );
  }

  if (
    !cpuObject ||
    !cpuObject.cpuArray ||
    cpuObject.cpuArray.length === 0 ||
    cpuObject.cpuArray[0].cpuUsrData.length === 0
  ) {
    throw new Error(
      "No CPU data could be extracted from this file.\nThe file may be incomplete or in an unsupported SAR format."
    );
  }
}

export async function callParse(fileContent) {
  validateSarContent(fileContent);

  const sarFileData = await readDataParallel(fileContent);
  const results = await pparseAllParallel(sarFileData);

  validateParsedResults(results);

  const {
    cpuObject,
    memoryObject,
    swapObject,
    blockObject,
    networkObject,
    networkErrObject,
    pagingObject,
    fileDetails,
  } = results;

  return {
    cpuObject,
    memoryObject,
    swapObject,
    blockObject,
    networkObject,
    networkErrObject,
    pagingObject,
    fileDetails,
  };
}
